### ISSUE TITLE
Chantodo's Resolve set damage element

### ISSUE THREAD

**Issue by Lothrik** [d07RiV/d3planner#82] opened 2016-04-17 21:51 UTC
Chantodo's Resolve: Every second while in Archon form you expel a Wave of Destruction, dealing 350% weapon damage to enemies within 30 yards

Wave of Destruction's damage element is determined by your gear: whatever the highest Elemental% damage type you have, that's the damage type it deals. However, the *amount* of damage it deals is increased by whatever Element type matches your Archon rune.

This means that if you only have elemental% damage on two items and want your Wave of Destruction to do the maximum possible Fire damage, you want 20% fire on one item, and 19% arcane on another.

More info: http://www.diablofans.com/forums/diablo-iii-class-forums/wizard-the-ancient-repositories/127024-2-3-vyrs-chantodos-set-mechanics-faqs

This is currently handled incorrectly by the simulator, and is immediately obvious if you're using Chantodo's Resolve with Firebirds, as the Wave of Destruction will never do Fire damage in the simulation no matter how much Fire% you have on your gear without you selecting the Fire Archon rune. If you have no other sources of Fire damage you'll be sitting at zero Firebird stacks the entire simulation.

**Comment by dominiklohmann** [comment] 2016-04-17 21:53
Duplicate of the last post in #47.

**Comment by d07RiV** [comment] 2016-04-21 23:59
Should be fixed now.

**Closed by d07RiV** 2016-04-21 23:59 UTC
