### ISSUE TITLE
No calculation when I add my character

### ISSUE THREAD

**Issue by Cry-Steffen** [d07RiV/d3planner#407] opened 2019-08-23 08:58 UTC
Hello,

first of all I want to say thank you for this awesome page. I am using it since years!

If I import my character nothing gets calculated. I also do not see any Statboxes when I go with my mouse over a item. 

Could you check that, please? Thank you!

**Comment by logam555** [comment] 2019-08-23 10:46
I reported the cause of the problem in #406 If you want to do a quick fix till the bug gets patched just remove legendary gems since they are the cause. I made a list of the working legendary gems in #406 but it is only 4 gems and 2 of them don't work if they are over level 25. Hopefully, the build you are looking at doesn't have a required legendary gem to work (Invoker for example).

**Comment by d07RiV** [comment] 2019-08-23 19:55
Should be fixed now.

**Comment by lordep** [comment] 2019-08-23 19:59
> 
> 
> Should be fixed now.

No (( Work only if delete legendary gems.

**Comment by d07RiV** [comment] 2019-08-23 20:11
Probably cached version, I cleared cloudflare cache for that script, seems to work for me now.

**Comment by lordep** [comment] 2019-08-24 04:16
> 
> 
> Probably cached version, I cleared cloudflare cache for that script, seems to work for me now.
> 
> I also just moved to a new server, which should help with the load within the next few days.
Now work fine, thanks for your work.

**Comment by logam555** [comment] 2019-08-24 09:17
Thanks for the work, hope my report was helpful in solving the issue. :)

**Closed** 2019-08-24 20:29 UTC
